name: dexhand

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [26]
      type: low_dim
  action:
    shape: [26]


dataset:
  _target_: diffusion_policy_3d.dataset.tiangong_dex_dataset_3d.TiangongDexDataset3D
  zarr_path: data/tiangong_dexhand_1_traj.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 90

  num_points: ${policy.pointcloud_encoder_cfg.num_points}
